server:
  ip: 127.0.0.1
  port: 8080

coin:
  name: aria
  symbol: aro
  algo: xevan
  blocktime: 24

rpc:
  ip: 127.0.0.1
  username: nur1labsltd
  password: 7{RQEA!^W+ZG+4w6
  port: 46031

zmq:
  endpoint: tcp://127.0.0.1:28332

mongo:
  ip: 127.0.0.1
